### ISSUE TITLE
支持dalao，但是有点问题。。无法创建文件 还有就是数组下限错误

### ISSUE THREAD

**Issue by 1354961639** [k0np4ku/Azurlane-scripts-autopatcher#1]
win10 x64系统 
无法创建文件，非法字符 还有就是数组下限错误，希望能修复下。。
![qq 20180617194127](https://user-images.githubusercontent.com/22723142/41507528-7704e572-7266-11e8-964f-2ae91125bf9b.png)
![qq 20180617194259](https://user-images.githubusercontent.com/22723142/41507537-a6cd5078-7266-11e8-89f9-b279e631ce6b.png)

**Comment by k0np4ku** [comment]
Change system locale to English (United States)

**Comment by 1354961639** [comment]
thanks
