### ISSUE TITLE
stuck at loading 

### ISSUE THREAD

**Issue by tempetahu0** [k0np4ku/Azurlane-scripts-autopatcher#2]
so i already edit the assembly C sharp with your guide (deleting things)
but it's still stuck at first login after placing the modded scripts

**Comment by k0np4ku** [comment]
1. Do you got any `exception-detected` or `out of bound array exception` when using the tool? 
2. Which version of the game? `JP/CN/KR`

**Comment by tempetahu0** [comment]
1. yeah i got those out of bound arrays, so it's not normal?
2. newest CN

**Comment by k0np4ku** [comment]
Yes, it's not normal.

Currently there's no solution to this issue. Maybe the code sucks and bad written, but it's working as intended to some people (including myself), or maybe your system missing some important components such as certain version of **Microsoft Visual C++** to run **luajit.exe**, I don't really know, or maybe you can try **Azurlane-LuaHelper** and try doing everything by yourself.

**Comment by Zeonzilt** [comment]
I am too stuck at loading 

Game Version JP

**Comment by tempetahu0** [comment]
now i have a new problems, i can now load it with modded scripts from someone but it's stuck at login with error number id : 31009, 31008, and 31007.

**Comment by k0np4ku** [comment]
I've released a new version and fixed the issue, but I don't know if it's working for you, so a little feedback will help.
